- CHANGELOG.md
- package-lock.json
- package.json
@9999years & @josephsumabat, do y'all read typescript? if so would you mind looking over this repo (not just this pull request) and check that my code is sensible and idiomatic? thanks!
> change repositories

- CHANGELOG.md
- package-lock.json
- package.json
> Release version 2.0.1

- CHANGELOG.md
- package-lock.json
- package.json
> Release version 2.0.3

- CHANGELOG.md
- src/annotations.ts
- src/client.ts
* Fix bug in annotations file paths.
* Fix bug in annotations where diagnostics collection are not cleaned up correctly.
* Give each annotations file its own diagnostics collection.
> Annotations fixes and improvements.

- CHANGELOG.md
- package-lock.json
- package.json
> Release version 2.1.0

- package-lock.json
- package.json
> Release version 2.1.1

- package-lock.json
- package.json
> Release version 2.2.0

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
> Release version 2.3.0

- package-lock.json
- package.json
> Release version 2.4.0

- package-lock.json
- package.json
> Release version 2.5.1

- package-lock.json
- package.json
> Release version 2.6.0

- package-lock.json
- package.json
> Release version 3.0.0

- package-lock.json
- package.json
> Release version 3.0.1

- CHANGELOG.md
- package-lock.json
- package.json
> Release version 3.0.3

- CHANGELOG.md
- package-lock.json
- package.json
> Release version 3.1.0

- CHANGELOG.md
- package-lock.json
- package.json
> Release version 3.2.0

- CHANGELOG.md
- package-lock.json
- package.json
> Release version 3.2.1

- CHANGELOG.md
- package-lock.json
- package.json
> Release version 3.2.2

- CHANGELOG.md
- package-lock.json
- package.json
> Release version 3.2.3

- CHANGELOG.md
- package-lock.json
- package.json
> Release version 3.2.4

- CHANGELOG.md
- package-lock.json
- package.json
> Release version 4.0.0

- src/client.ts
- src/config.ts
This will let people add `--enableInlays` to their `static-ls` options!
> Add `serverArgs`

- .github/workflows/release.yaml
- package.json
Adds a mercury managed token for marketplace publishing
> Update marketplace token for publishing

- CHANGELOG.md
- package-lock.json
- package.json
> Release version 4.0.1

- package.json
This will allow us to re-publish on vscode marketplace
> Rename package id

- CHANGELOG.md
- package-lock.json
- package.json
> Release version 4.0.2

- CHANGELOG.md
- package-lock.json
- package.json
> Release version 4.0.3

- src/config.ts
- src/extension.ts
- src/utils.ts
On vs-code reload for some people alloglot continues running in the background leaving multiple hanging processes until vscode is fully restarted. This PR implements a proper disposable method to clean up the old process.
> disposable fix
